version: '3.8'

services:

  postgres-db:
    image: postgres:16
    container_name: prescription-system-db
    environment:
      POSTGRES_USER: gif
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: cafe
    ports:
      - "49154:5432"
    networks:
      - prescription-network  
networks:
  prescription-network:
    driver: bridge


